/**
 * Shared receipt JSON parsing and auto-correction utilities.
 * Used by both geminiAdapter and claudeAdapter.
 */

import type { ParsedReceipt } from '../../types/receipt.types';
import _autoCorrections from '../../data/autoLearnedCorrections.json';

// Nested format: { "_global": { ocrText: correct }, "restaurant key": { ocrText: correct } }
// Generated by `npm run regression:learn` — bundled at build time by Vite.
const AUTO_CORRECTIONS = _autoCorrections as Record<string, Record<string, string>>;

/**
 * Apply auto-learned corrections to every item name in the receipt.
 * Looks up corrections in two scopes (merged, scoped wins on conflict):
 *   1. "_global" — applies to every receipt regardless of restaurant
 *   2. restaurantKey — restaurant-specific corrections from the golden files
 */
export function applyAutoCorrections(receipt: ParsedReceipt): ParsedReceipt {
  const global        = AUTO_CORRECTIONS['_global'] ?? {};
  const restaurantKey = receipt.restaurantName?.trim().toLowerCase() ?? '';
  const scoped        = restaurantKey ? (AUTO_CORRECTIONS[restaurantKey] ?? {}) : {};
  const combined      = { ...global, ...scoped }; // scoped overrides global on conflict
  if (!Object.keys(combined).length) return receipt;
  return {
    ...receipt,
    items: receipt.items.map(item => ({
      ...item,
      name: combined[item.name] ?? item.name,
    })),
  };
}

/**
 * Parse a raw JSON string returned by an LLM into a ParsedReceipt.
 * Strips markdown code fences that some providers wrap JSON in.
 */
export function parseReceiptJSON(text: string): ParsedReceipt {
  const clean = text.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/, '').trim();
  let parsed: ParsedReceipt & { error?: string };
  try   { parsed = JSON.parse(clean); }
  catch { console.error('[adapter] bad JSON:', text); throw new Error('PARSE_ERROR'); }
  if (parsed.error) throw new Error(parsed.error);
  return parsed;
}
